### PR TITLE
feat: support customized logger for Boomer, Output and runner

### PR DESCRIPTION
**Pull request by zezhehh**
The new feature is totally backwards compatible, while it allows user to customize the logger for `Boomer`, `Output` and `runner`.

Added:
- `func (b *Boomer) WithLogger(logger *log.Logger) *Boomer`
- `func (o *XxxOutput) WithLogger(logger *log.Logger) *XxxOutput`

### CODE REVIEW

**Comment by myzhan** [comment]
Please make sure the tests are passed.

**Comment by zezhehh** [comment]
> Please make sure the tests are passed.

Could you approve the workflow again? Local tests work now with default loggers added.

**Comment by zezhehh** [comment]
hmmmm, I have no idea why the windows one failed, but I can add tests for `WithLogger`, which probably increases the coverage. Should I?

**Comment by myzhan** [comment]
> hmmmm, I have no idea why the windows one failed, but I can add tests for `WithLogger`, which probably increases the coverage. Should I?

I think the windows machine make some time-sensitive testcases flaky, your changes are not related. Yes, you can add testcases for WithLogger.

**Comment by zezhehh** [comment]
> > hmmmm, I have no idea why the windows one failed, but I can add tests for `WithLogger`, which probably increases the coverage. Should I?
> 
> I think the windows machine make some time-sensitive testcases flaky, your changes are not related. Yes, you can add testcases for WithLogger.

@myzhan Hopefully it's green for Codecov this time.

**Comment by zezhehh** [comment]
Let's go ahead and merge it! If it works for you @myzhan  :D

**Pull request merged**
