### PR TITLE
add support for czmq sockets and main.go to examples

### PR DESCRIPTION
**Pull request by marrotte**

### CODE REVIEW

**Comment by marrotte** [comment]
This PR addresses issue #2 https://github.com/myzhan/boomer/issues/2

**Comment by myzhan** [comment]
Thanks for your help! I will review this feature ASAP.

**Comment by marrotte** [comment]
is there a way I can contact u about a job?

**Comment by myzhan** [comment]
Hi @marrotte , a zeromq client can subcribe to a tcp address without a started server. It means that your code won't fallback to go socket imp as you expect.

In case of mixing up zeromq and go socket, I added a new command line option "rpc", which defaults to zeromq.

And, you can contact me via scau.myzhan@gmail.com.

**Comment by myzhan** [comment]
Hi @marrotte , FYI, I just made zeromq optional.

From now on, you need to add tag "zeromq" to build Boomer with zeromq support.

go build -tags 'zeromq' -o a.out main.go

**Pull request merged**
